spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dndPrivate?useSSL=false&allowPublicKeyRetrieval=true
    username: kdo6301
    password: rlaehddnd0422@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
